@startuml Describe infrastructure
'https://plantuml.com/sequence-diagram

autonumber

participant Client #aliceblue
participant DescribeInfra as Infra #aliceblue
participant VpcHelper as Vpc
participant SubnetHelper as Subnet
participant SecurityGroupHelper as SecurityGroup
participant KeyPairHelper as KeyPair
participant InstanceHelper as Instance

note right Client
VIR1_deliver
Describe infrastructure
Author : Yannick Baudraz
Date : 2022-06-09
end note

Client -> Infra: describe(vpcName)

Infra -> Vpc : describe(VpcName)
Vpc --> Infra : vpc information

Infra -> Subnet : describe(vpcName)
Subnet --> Infra : subnet information

Infra -> SecurityGroup : describe(vpcName)
SecurityGroup --> Infra : security groups information

Infra -> KeyPair : describe(keyName)
KeyPair --> Infra : key pairs information

Infra -> Instance : describe(instanceName)
Instance --> Infra : instances information

Infra --> Client : Json string containing all information\nabout the infrastructure

@enduml
