@startuml
skinparam classAttributeIconSize 0

note as t1
VIR1_deliver
Class diagram
Authors
    Yannick Baudraz
    Armand Marechal
Date : 2022-06-16
end note

class Infra as "DescribeInfra" #aliceblue {
    +constructor(awsClient : AwsCloudClientImpl)
    +describe(vpcName : String) : string
}

class Credentials #aliceblue {
    +constructor(awsClient : AwsCloudClientImpl)
    +describe(instanceName : String) : object[]
}

class VpcHelper {
    +constructor(awsClient : AwsCloudClientImpl)
    +exists(vpcName : string) : boolean
    +describe(vpcName : String) : object
}

class SubnetHelper {
    +constructor(awsClient : AwsCloudClientImpl)
    +exists(vpcName : string) : boolean
    +describe(vpcName : String) : object[]
}

class SecurityGroupHelper {
    +constructor(awsClient : AwsCloudClientImpl)
    +exists(securityGroupName : string) : boolean
    +describe(vpcName : String) : object[]
}

class InstanceHelper {
    +constructor(awsClient : AwsCloudClientImpl)
    +exists(instanceName : string) : boolean
    +describe(instanceName : String) : object[]
}

class KeyPairHelper {
    +constructor(awsClient : AwsCloudClientImpl)
    +exists(instanceName : string) : boolean
    +describe(instanceName : String) : object[]
}

class WindowsPasswordHelper {
    +constructor(awsClient : AwsCloudClientImpl)
    +describe(instanceName : String) : object[]
}

package core {
    interface ICloudClient {
        +describe(vpcName : String) : string
    }

    class AwsCloudClientImpl implements ICloudClient {
        +constructor()
        +describe(vpcName : String) : string
    }
}

together {
    class Error
    class VpcException
    class VpcNotFoundException
    class InstanceException
    class InstanceNotFoundException
    class UnavailableInstancePasswordsException
}

AwsCloudClientImpl *-- Infra
AwsCloudClientImpl *-- Credentials

Infra ..> VpcHelper
Infra ..> SubnetHelper
Infra ..> SecurityGroupHelper
Infra ..> InstanceHelper
Infra ..> KeyPairHelper

Credentials ..> WindowsPasswordHelper
Credentials ..> KeyPairHelper

VpcException --|> Error
VpcNotFoundException --|> VpcException
InstanceException --|> Error
InstanceNotFoundException --|> InstanceException
UnavailableInstancePasswordsException --|> InstanceException

SubnetHelper ..> VpcHelper
SecurityGroupHelper ..> VpcHelper
WindowsPasswordHelper ..> InstanceHelper

VpcHelper ..> VpcNotFoundException
InstanceHelper ..> InstanceNotFoundException
WindowsPasswordHelper ..> InstanceNotFoundException
WindowsPasswordHelper ..> UnavailableInstancePasswordsException

@enduml
