@startuml
skinparam classAttributeIconSize 0

note as t1
VIR1_deliver
Class diagram
Authors
    Yannick Baudraz
    Armand Marechal
Date : 2022-06-18
end note

package deliver {
    class Infra as "DescribeInfra" #aliceblue {
        +constructor(awsClient : AwsCloudClientImpl)
        +describe(vpcName : String) : String
    }

    class Credentials #aliceblue {
        +constructor(awsClient : AwsCloudClientImpl)
        +describeLinuxSshKeys() : void
        +describeWindowsPasswords() : void
    }

    class VpcHelper {
        +constructor(awsClient : AwsCloudClientImpl)
        +describe(vpcName : String) : object
    }

    class SubnetHelper {
        +constructor(awsClient : AwsCloudClientImpl)
        +describe(vpcName : String) : object[]
    }

    class SecurityGroupHelper {
        +constructor(awsClient : AwsCloudClientImpl)
        +describe(vpcName : String, securityGroupName = " " : String) : object[]
    }

    class InstanceHelper {
        +constructor(awsClient : AwsCloudClientImpl)
        +describe(instanceName : String) : object[]
        +describeWindowsInstances() : object[]
    }

    class KeyPairHelper {
        +constructor(awsClient : AwsCloudClientImpl)
        +describe() : object[]
    }

    class WindowsPasswordHelper {
        +constructor(awsClient : AwsCloudClientImpl)
        +describe() : object[]
    }

    together {
        class Error
        class VpcException
        class VpcNotFoundException
        class InstanceException
        class InstanceNotFoundException
    }
}

package core {
    interface ICloudClient {
        +describe(vpcName : String) : String
    }

    class AwsCloudClientImpl implements ICloudClient {
        +constructor()
        +describe(vpcName : String) : String
    }
}

AwsCloudClientImpl *-- Infra
AwsCloudClientImpl *-- Credentials
AwsCloudClientImpl *-- VpcHelper
AwsCloudClientImpl *-- SubnetHelper
AwsCloudClientImpl *-- SecurityGroupHelper
AwsCloudClientImpl *-- InstanceHelper
AwsCloudClientImpl *-- KeyPairHelper
AwsCloudClientImpl *-- WindowsPasswordHelper

Infra ..> VpcHelper
Infra ..> SubnetHelper
Infra ..> SecurityGroupHelper
Infra ..> InstanceHelper
Infra ..> KeyPairHelper

Credentials ..> WindowsPasswordHelper
Credentials ..> KeyPairHelper

VpcException --|> Error
VpcNotFoundException --|> VpcException
InstanceException --|> Error
InstanceNotFoundException --|> InstanceException

SubnetHelper ..> VpcHelper
SecurityGroupHelper ..> VpcHelper
WindowsPasswordHelper ..> InstanceHelper

VpcHelper ..> VpcNotFoundException
InstanceHelper ..> InstanceNotFoundException

@enduml
